# Generated by Django 4.2.6 on 2024-04-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='code',
            field=models.CharField(default='db9bc363', max_length=8),
        ),
    ]
